events {
    worker_connections 1024;
}

http {
    resolver 8.8.8.8 valid=30s;

    upstream backend {
        server techstore-api-1-5grr.onrender.com:443 max_fails=3 fail_timeout=30s;
        server proyectoad2.onrender.com:443 max_fails=3 fail_timeout=30s backup;
    }

    server {
        listen 80;

        location / {
            proxy_pass https://backend;
            proxy_set_header Host techstore-api-1-5grr.onrender.com;
            proxy_ssl_server_name on;
            proxy_ssl_name techstore-api-1-5grr.onrender.com;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_redirect off;
        }
    }
}
